# Generated by Django 5.0.2 on 2024-02-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='product_images/')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
