# Generated by Django 5.0.2 on 2024-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_product_rename_category_addproduct_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
