# Generated by Django 5.0.2 on 2024-03-04 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 14, 48, 2, 941628)),
        ),
    ]
