# Generated by Django 5.0.2 on 2024-03-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.CharField(default='datetime.now()', max_length=50),
        ),
    ]
