# Generated by Django 5.0.2 on 2024-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_alter_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(max_length=20)),
                ('combo_price', models.IntegerField()),
                ('combo_products', models.ManyToManyField(to='testing.product')),
            ],
        ),
        migrations.DeleteModel(
            name='addData',
        ),
        migrations.DeleteModel(
            name='AddProduct',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
